<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Saved Trade and other accounts receivab_314fa4</name>
   <tag></tag>
   <elementGuidId>b19cc5a0-a9a3-4c36-a91d-77de81487f4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ng-tns-c2308121496-136.toast-message.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-container']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Saved 'Trade and other accounts receivable' successfully&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b7be0dde-7f93-475c-9f79-f0200bfe4a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>2034fb92-2e00-4913-9d03-6f58a560ae73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c2308121496-136 toast-message ng-star-inserted</value>
      <webElementGuid>5cc3b8cb-81a2-474e-bbf8-2bcdb60d196f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Saved 'Trade and other accounts receivable' successfully</value>
      <webElementGuid>8445d358-321a-4288-b897-7d5a62bb135c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Saved 'Trade and other accounts receivable' successfully </value>
      <webElementGuid>e6cd11ef-2edc-4e57-9d7e-5c02136289e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-container&quot;)/div[@class=&quot;ng-tns-c2308121496-136 ng-star-inserted ng-trigger ng-trigger-flyInOut ngx-toastr toast-success&quot;]/div[@class=&quot;ng-tns-c2308121496-136 toast-message ng-star-inserted&quot;]</value>
      <webElementGuid>d09f5865-60b9-4fec-ab09-b226f5475957</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-container']/div/div</value>
      <webElementGuid>772aa6d1-1445-4d03-b149-53affda82548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clear'])[2]/following::div[5]</value>
      <webElementGuid>a5e1c3e0-6e0e-474d-bf2b-bf1074c7e215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clear'])[1]/following::div[11]</value>
      <webElementGuid>fc95fc4a-bf3a-41f4-b3b5-37c2369e262b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>007b0269-a212-4c86-85fe-dd45e04b2a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot; Saved &quot; , &quot;'&quot; , &quot;Trade and other accounts receivable&quot; , &quot;'&quot; , &quot; successfully &quot;) or . = concat(&quot; Saved &quot; , &quot;'&quot; , &quot;Trade and other accounts receivable&quot; , &quot;'&quot; , &quot; successfully &quot;))]</value>
      <webElementGuid>f9b90472-79ea-4533-9367-0ceb6a00022a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
