<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Engagements</name>
   <tag></tag>
   <elementGuidId>ea4de1b2-25e0-4bbd-a757-77e2f76815e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Templates'])[2]/following::div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ng-value-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Engagements$/ >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c17c082e-a79d-42f6-bbba-03931e153976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-value-container</value>
      <webElementGuid>8559c256-a1de-4de7-baab-f8cbb2034c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Engagements</value>
      <webElementGuid>ac2b29ba-358f-4b3c-ab6e-fa1d38555c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dasboard-container layout-dashboard drawer-small&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;dashboard-main&quot;]/app-templates-dashboard[@class=&quot;ng-star-inserted&quot;]/mat-drawer-container[@class=&quot;mat-drawer-container countable-drawer templates mat-drawer-container-has-open&quot;]/mat-drawer[@class=&quot;mat-drawer ng-tns-c2384444419-50 ng-trigger ng-trigger-transform mat-drawer-over mat-drawer-opened ng-star-inserted&quot;]/div[@class=&quot;mat-drawer-inner-container ng-tns-c2384444419-50&quot;]/div[@class=&quot;template-block-main gap-20 ng-tns-c2384444419-50&quot;]/div[@class=&quot;ng-form-field w-100 px-3&quot;]/ng-select[@class=&quot;template-select icon-dropdown hide-input ng-select-searchable ng-select ng-select-single ng-untouched ng-pristine ng-valid ng-select-opened ng-select-bottom&quot;]/div[@class=&quot;ng-select-container ng-has-value&quot;]/div[@class=&quot;ng-value-container&quot;]</value>
      <webElementGuid>494a2f8b-e7bb-4463-97d6-65ea5d2d6261</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Templates'])[2]/following::div[3]</value>
      <webElementGuid>a60fad9e-0533-48ca-a7ff-8598422d240b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hardayal Sharma'])[2]/following::div[10]</value>
      <webElementGuid>a7338013-5d85-4d21-9780-15f28ac13e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Engagements'])[3]/preceding::div[5]</value>
      <webElementGuid>e5b5f228-1d05-4ff9-9c95-39d456fc92a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-select/div/div</value>
      <webElementGuid>546b61bd-44bd-44d5-a122-a5b9c455f753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Engagements' or . = 'Engagements')]</value>
      <webElementGuid>386753c3-064b-4573-9039-11d810c0cce1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
