<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Automated notes can only be copied once</name>
   <tag></tag>
   <elementGuidId>8df7a906-cf88-48a8-8cbb-e2bce2e6e202</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-container']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ng-tns-c2308121496-139.toast-message.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Automated notes can only be copied once.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f9c7ccfc-ad18-48fe-889f-b0c7264de91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>95d0354e-7184-45fd-aa57-f7b04e53a207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c2308121496-139 toast-message ng-star-inserted</value>
      <webElementGuid>3715730f-c446-4c99-9754-df33cabd279b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Automated notes can only be copied once.</value>
      <webElementGuid>562bc79e-4f23-4980-89a2-ac8b70670281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Automated notes can only be copied once. </value>
      <webElementGuid>b1cbd2d8-e6c0-40cc-ae86-c5b1410c8da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-container&quot;)/div[@class=&quot;ng-tns-c2308121496-139 ng-star-inserted ng-trigger ng-trigger-flyInOut ngx-toastr toast-warning&quot;]/div[@class=&quot;ng-tns-c2308121496-139 toast-message ng-star-inserted&quot;]</value>
      <webElementGuid>f2e1eafd-267a-4723-9eaa-87f29c25be67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-container']/div/div[2]</value>
      <webElementGuid>9516766e-d3d2-4388-95a2-39d50bb2a72f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note(s) already exists in the Firm Templates.'])[1]/following::div[1]</value>
      <webElementGuid>a7863324-f8d2-465c-8f15-6d1f3a0b64fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clear'])[2]/following::div[7]</value>
      <webElementGuid>8e9f3247-2cd0-4be5-b716-4305a91011ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Automated notes can only be copied once.']/parent::*</value>
      <webElementGuid>cd7e5af6-d644-4be7-8010-a707cf2acf64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]</value>
      <webElementGuid>45906284-e187-4d84-86ba-37f95361b174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Automated notes can only be copied once. ' or . = ' Automated notes can only be copied once. ')]</value>
      <webElementGuid>39fc899c-3462-479c-bc78-1b373d5ab477</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
