<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Folder_name</name>
   <tag></tag>
   <elementGuidId>2571dd43-ccf9-4b75-86f1-d11587d83152</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-mdc-form-field-infix.ng-tns-c1798928316-131 > #name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Enter folder name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter folder name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e1fe8b0-25ef-4082-b691-fce2d188ad98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>copyMasterNoteFormNewFolder</value>
      <webElementGuid>da47c163-1a71-48ec-b7d0-a2f0cd1a20bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>352</value>
      <webElementGuid>3b1e562b-9a74-4a3a-b9ae-df212af51399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>f5ca79b1-bc6e-4b44-aead-c5c7715d4084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter folder name</value>
      <webElementGuid>f2f021a9-1e2b-4c60-9ed6-76eb7f3bd271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-input-element ng-tns-c1798928316-131 ng-untouched ng-pristine mat-mdc-form-field-input-control mdc-text-field__input cdk-text-field-autofill-monitored ng-invalid</value>
      <webElementGuid>9145dae1-efff-424a-a771-9114dbfc2359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f998fd0d-6fc1-4225-a834-e1b034a15ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-dialog-0&quot;)/div[@class=&quot;mdc-dialog__container&quot;]/div[@class=&quot;mat-mdc-dialog-surface mdc-dialog__surface&quot;]/form[@class=&quot;ng-star-inserted ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;countable-dialog w-400 notes-copy-master-template-dialog add-temp-dialog&quot;]/div[@class=&quot;dialog-body-content gap-20&quot;]/div[@class=&quot;ng-star-inserted&quot;]/mat-form-field[@class=&quot;mat-mdc-form-field fixed-label w-100 ng-tns-c1798928316-131 mat-mdc-form-field-type-mat-input mat-mdc-form-field-label-always-float mat-form-field-appearance-fill mat-primary ng-untouched ng-pristine ng-star-inserted ng-invalid mat-focused&quot;]/div[@class=&quot;mat-mdc-text-field-wrapper mdc-text-field ng-tns-c1798928316-131 mdc-text-field--filled mdc-text-field--focused&quot;]/div[@class=&quot;mat-mdc-form-field-flex ng-tns-c1798928316-131&quot;]/div[@class=&quot;mat-mdc-form-field-infix ng-tns-c1798928316-131&quot;]/input[@id=&quot;name&quot;]</value>
      <webElementGuid>6151827d-3484-4f4b-9ec8-7bc678cf723d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='name'])[2]</value>
      <webElementGuid>e0e22a93-e5f7-4574-a168-7603cf2c191f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-mdc-dialog-0']/div/div/form/div/div[2]/div/mat-form-field/div/div[2]/div/input</value>
      <webElementGuid>c2aab4b8-7be7-4fbf-ae42-f5737fb9db85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/mat-form-field/div/div[2]/div/input</value>
      <webElementGuid>38c6c101-9505-4c3a-a5fd-f393ee3d5bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'copyMasterNoteFormNewFolder' and @id = 'name' and @placeholder = 'Enter folder name']</value>
      <webElementGuid>1444f5cb-6249-486f-b09f-aa857f31156f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
