<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PSP_Katalon_1</name>
   <tag></tag>
   <elementGuidId>bec1570b-1387-454e-a6da-a527b59c0ab4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@title='PSP_Katalon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.item-title.ellipse.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Toogle PSP_Katalon menu&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0c344fe5-f8b1-4aff-93b3-54b3529aa4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-title ellipse ng-star-inserted</value>
      <webElementGuid>f2123372-6a8f-4eb4-bdb7-7344e6d50cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PSP_Katalon</value>
      <webElementGuid>1ba4eefe-a035-4e60-bd3a-6531e48a8124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> PSP_Katalon</value>
      <webElementGuid>bfa39c56-deda-4406-9d8e-dbc7b46adb32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-expansion-panel-header-27&quot;)/span[@class=&quot;mat-content ng-tns-c1676997785-98&quot;]/mat-panel-title[@class=&quot;mat-expansion-panel-header-title ng-tns-c1676997785-98&quot;]/div[@class=&quot;title-content&quot;]/span[@class=&quot;item-title ellipse ng-star-inserted&quot;]</value>
      <webElementGuid>322bb190-ce1a-4efa-9a69-dc0288f93e2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-27']/span/mat-panel-title/div/span[4]</value>
      <webElementGuid>94128b91-f56f-466a-a67d-a7d5279c4f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select all'])[1]/following::span[9]</value>
      <webElementGuid>2b0a86f8-66ed-4e69-a133-212d348d81c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Library'])[1]/following::span[25]</value>
      <webElementGuid>176436cb-14bd-49cc-a7d5-9f38e9f26de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advertising contracts (completed contract method)'])[1]/preceding::span[8]</value>
      <webElementGuid>4fddd449-21a7-4ba4-9005-97be3c5196b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advertising contracts (percentage of completion method)'])[1]/preceding::span[15]</value>
      <webElementGuid>d26f232c-2402-4441-8c17-b4e2cedd6a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PSP_Katalon']/parent::*</value>
      <webElementGuid>148994b0-3bb7-4cfe-ba48-eec61cdf9cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span[4]</value>
      <webElementGuid>5de47c2f-0941-4ddc-a496-0bc248707030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'PSP_Katalon' and (text() = ' PSP_Katalon' or . = ' PSP_Katalon')]</value>
      <webElementGuid>52a60405-ca00-463e-aecd-c521ea6428d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
