<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2</name>
   <tag></tag>
   <elementGuidId>43833239-2998-43b1-82bf-36c22dec2af6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mat-panel-title.mat-expansion-panel-header-title.ng-tns-c1676997785-2758 > div.title-content.hover-action > span.togglable-icon.ng-star-inserted > img[alt=&quot;Toogle&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-49']/span/mat-panel-title/div/span[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>19c5dcf5-261a-4613-b0fd-3f5566998149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/ui-uplift-icons/global/toggle-icon-up.svg</value>
      <webElementGuid>ab48fa7b-8898-4ecb-89e5-6af4952a642a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Toogle</value>
      <webElementGuid>7c6793c5-3d26-4e78-ba21-65231db4602e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-expansion-panel-header-49&quot;)/span[@class=&quot;mat-content ng-tns-c1676997785-2758&quot;]/mat-panel-title[@class=&quot;mat-expansion-panel-header-title ng-tns-c1676997785-2758&quot;]/div[@class=&quot;title-content hover-action&quot;]/span[@class=&quot;togglable-icon ng-star-inserted&quot;]/img[1]</value>
      <webElementGuid>07b7783d-32b8-417e-8b6a-1e858b035dda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-49']/span/mat-panel-title/div/span[3]/img</value>
      <webElementGuid>671394c3-543d-4d6d-beed-f042463a1e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Toogle'])[5]</value>
      <webElementGuid>f8989449-7e38-477c-8e30-8f110e681aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-expansion-panel[5]/mat-expansion-panel-header/span/mat-panel-title/div/span[3]/img</value>
      <webElementGuid>05c0a82c-a5cc-41ce-93d0-26ab1df33f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/ui-uplift-icons/global/toggle-icon-up.svg' and @alt = 'Toogle']</value>
      <webElementGuid>e33e13cd-fd4b-479e-93bc-5fd7824287cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
