<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>056ccf4d-bf72-4fda-83cf-344c9c970fb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mat-mdc-menu-trigger.button-text.hover-action-item.mdc-button.mat-mdc-button.mat-unthemed.mat-mdc-button-base.ng-star-inserted > span.mdc-button__label > img[alt=&quot;icon&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-49']/span/mat-panel-title/div/button[2]/span[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7f30c4ec-4f52-421e-91e7-ef0412065fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/ui-uplift-icons/global/plus-gray.svg</value>
      <webElementGuid>869c0137-3deb-4148-ac80-b1e27f5ab974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>1739985c-4ba1-4d3d-88c3-25858e0bd6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-expansion-panel-header-49&quot;)/span[@class=&quot;mat-content ng-tns-c1676997785-2758&quot;]/mat-panel-title[@class=&quot;mat-expansion-panel-header-title ng-tns-c1676997785-2758&quot;]/div[@class=&quot;title-content hover-action&quot;]/button[@class=&quot;mat-mdc-menu-trigger button-text hover-action-item mdc-button mat-mdc-button mat-unthemed mat-mdc-button-base ng-star-inserted&quot;]/span[@class=&quot;mdc-button__label&quot;]/img[1]</value>
      <webElementGuid>52308e28-b11c-4436-b025-595b1bb090d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-49']/span/mat-panel-title/div/button[2]/span[2]/img</value>
      <webElementGuid>8124ea97-8d0a-4dd5-be4b-27675a53d252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon'])[9]</value>
      <webElementGuid>b97a5f6b-1b5c-49a3-b9ca-cf2f97d2b27a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-expansion-panel[5]/mat-expansion-panel-header/span/mat-panel-title/div/button[2]/span[2]/img</value>
      <webElementGuid>3e2a3bde-1cdf-4308-ac77-260f6aa131c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/ui-uplift-icons/global/plus-gray.svg' and @alt = 'icon']</value>
      <webElementGuid>3ef521ad-873b-4d86-ac84-149433a18e9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
