<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_BPlBNFS</name>
   <tag></tag>
   <elementGuidId>6af05fbf-641f-4262-9527-7c91c3589d40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BPlBNFS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BPlBNFS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d25dc8cc-28b1-4623-875d-f048e0d01ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0eecbfa3-7f4f-4a7b-846c-7dd4e62e1299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Description here</value>
      <webElementGuid>7d6e3774-4eb5-4455-9bea-e49ed89cd3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-input-element ng-tns-c1798928316-2778 ng-untouched ng-pristine ng-valid mat-mdc-form-field-input-control mdc-text-field__input cdk-text-field-autofill-monitored</value>
      <webElementGuid>91d977df-06eb-4462-8555-9c27023439fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BPlBNFS</value>
      <webElementGuid>a601e5ba-43a3-4ab1-b09a-131121ca9d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9a71bd68-92da-44e2-98ed-186eda5e57a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fbb518bf-f947-4c9f-89db-d32c391db704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BPlBNFS&quot;)</value>
      <webElementGuid>e39ada49-eb73-4487-9c00-4c9d9ed23dbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BPlBNFS']</value>
      <webElementGuid>a0968cf9-38ba-4c30-a42c-5eee98665e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cdk-drop-list-34']/tbody/tr/td[2]/mat-form-field/div/div[2]/div/input</value>
      <webElementGuid>19f38de2-ea81-4b1c-926d-eec568c090db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/mat-form-field/div/div[2]/div/input</value>
      <webElementGuid>495d5d8c-8300-4408-a427-9f1e5e5d21a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Description here' and @id = 'BPlBNFS']</value>
      <webElementGuid>9a63c07a-fc52-4594-97a5-f255b59a286d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
