<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Category title_mat-input-2</name>
   <tag></tag>
   <elementGuidId>91b28666-070d-4e58-b1bd-067d99354a4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-input-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-input-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b08bfe4-8487-46ae-a491-8e3548e644fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Category Name</value>
      <webElementGuid>a37ce255-b9a5-42f5-b0b4-e4b1b04b3d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b2a03c4a-e934-4196-b3f0-18cc075aa83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-input-element ng-tns-c1798928316-2752 ng-untouched ng-pristine ng-invalid mat-mdc-form-field-input-control mdc-text-field__input cdk-text-field-autofill-monitored</value>
      <webElementGuid>27dda862-f680-4605-8da7-68bbbc3735c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-2</value>
      <webElementGuid>26dae0da-1b03-4d0c-a5e3-71570d9c5e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bbbb273a-9b97-4bfb-9d2b-30c63956f4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-2&quot;)</value>
      <webElementGuid>95c30a80-d790-4bbf-a30e-1cd2b114196f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-2']</value>
      <webElementGuid>6473fb9f-1c24-4926-88d7-345ace416240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-mdc-dialog-1']/div/div/div/div[2]/mat-form-field/div/div[2]/div/input</value>
      <webElementGuid>b5163e1d-e423-4e25-8d4d-81f967926d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/mat-form-field/div/div[2]/div/input</value>
      <webElementGuid>7f4b49f9-d537-4ae5-b67f-00503fb5da12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Category Name' and @id = 'mat-input-2']</value>
      <webElementGuid>a3495c86-817c-44a4-a68a-9fe70d36bcbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
