<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add notes (1)</name>
   <tag></tag>
   <elementGuidId>8772056a-90e2-47c6-b09a-0ab0eaee324e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button-medium.mdc-button.mat-mdc-button.mdc-button--unelevated.mat-mdc-unelevated-button.mat-primary.mat-mdc-button-base.cdk-focused.cdk-mouse-focused > span.mdc-button__label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-mdc-dialog-3']/div/div/div/div[3]/div/button/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8b54eee7-8753-489b-af95-e1d994eb10d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-button__label</value>
      <webElementGuid>e7f25a8f-f170-42c4-8b7c-14fa4a8c8127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add notes (1)</value>
      <webElementGuid>fdb88469-ac9e-4a5d-a6d8-3962f4d6aa02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-dialog-3&quot;)/div[@class=&quot;mdc-dialog__container&quot;]/div[@class=&quot;mat-mdc-dialog-surface mdc-dialog__surface&quot;]/div[@class=&quot;notesFSImport countable-dialog template-block-main right-drawer ng-star-inserted&quot;]/div[@class=&quot;mat-dialog-actions w-100&quot;]/div[@class=&quot;dialog-footer d-flex flex-row flex-nowrap align-items-center justify-content-end&quot;]/button[@class=&quot;button-medium mdc-button mat-mdc-button mdc-button--unelevated mat-mdc-unelevated-button mat-primary mat-mdc-button-base cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mdc-button__label&quot;]</value>
      <webElementGuid>0ffd18ef-94bc-4ec6-9870-90865bdf3edf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-mdc-dialog-3']/div/div/div/div[3]/div/button/span[2]</value>
      <webElementGuid>f44b2b6f-79f4-4196-9d7a-43d2e70eee7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Text note'])[1]/following::span[2]</value>
      <webElementGuid>ba15c1aa-decb-4e1b-8bbd-8556b6b0dc38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Text Folder test'])[1]/following::span[6]</value>
      <webElementGuid>bcf98372-b7e4-49f6-bb41-dfdae4334b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add notes (1)']/parent::*</value>
      <webElementGuid>ad4baead-1739-47ca-9d22-9c2882777bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button/span[2]</value>
      <webElementGuid>8b6b1bd1-d62c-4d5e-9f06-671d3b8057b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Add notes (1)' or . = 'Add notes (1)')]</value>
      <webElementGuid>2fdc0dbf-f9b6-4126-8a4b-7113bef5c219</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
