<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Total</name>
   <tag></tag>
   <elementGuidId>46121fdb-b937-4a5e-bca8-a696562b686c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mat-mdc-menu-item.mat-mdc-focus-indicator.mat-mdc-menu-trigger.ng-star-inserted.ng-tns-c681116372-2769.cdk-focused.cdk-mouse-focused > span.mat-mdc-menu-item-text > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-menu-panel-2654']/div/button[4]/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e120280a-0fd6-4c94-8508-f901243f056d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Total</value>
      <webElementGuid>ff0116c3-e2bc-495a-9d3a-ae302c019575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-menu-panel-2654&quot;)/div[@class=&quot;mat-mdc-menu-content ng-tns-c681116372-2769&quot;]/button[@class=&quot;mat-mdc-menu-item mat-mdc-focus-indicator mat-mdc-menu-trigger ng-star-inserted ng-tns-c681116372-2769 cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-mdc-menu-item-text&quot;]/span[1]</value>
      <webElementGuid>74ae2642-f97a-40db-ba2e-4fa8748f42db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-menu-panel-2654']/div/button[4]/span/span</value>
      <webElementGuid>de5289d0-6d71-424d-9a68-98e4bdc1c44d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual'])[4]/following::span[2]</value>
      <webElementGuid>cb7ec2ef-18c8-4fe3-9a1f-cba3be312510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prior Year'])[1]/following::span[4]</value>
      <webElementGuid>dc9cef02-7db8-4844-86db-9d9061dc1f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]/span/span</value>
      <webElementGuid>a1593b60-18e4-444e-8f97-4d989326ce83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Total' or . = 'Total')]</value>
      <webElementGuid>195e80fe-cec7-4141-b476-85d23ab82d67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
