<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Manual_Colm2_Kebab</name>
   <tag></tag>
   <elementGuidId>1b82d9cb-5593-4dac-9cba-9fd7c6e0eb11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr/th[5]/span/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
