<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add_Notes_On_Popup</name>
   <tag></tag>
   <elementGuidId>4774f9ae-30a8-4d3f-9d99-2efa5dbf7002</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div/button[@color='primary'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
