<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete_Individual_Note_WB</name>
   <tag></tag>
   <elementGuidId>429e3f49-7ed0-46bf-a1a8-1c7cea0b2a44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>((//div/div/mat-accordion/mat-expansion-panel/mat-expansion-panel-header)[1]/span/mat-panel-title/div/button)[2]&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
