<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Format</name>
   <tag></tag>
   <elementGuidId>1cbe71bc-fe36-43b6-adbc-d330e2fe8094</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mat-mdc-menu-item.mat-mdc-focus-indicator.mat-mdc-menu-trigger.add-row-btn.ng-tns-c681116372-387.ng-star-inserted.cdk-focused.cdk-mouse-focused > span.mat-mdc-menu-item-text > div.flexbox-row.gap-8.justify-content-between</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-menu-panel-315']/div/button[2]/span/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>512dd033-1674-481a-b272-01167e8f44d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flexbox-row gap-8 justify-content-between</value>
      <webElementGuid>9f749e9f-a718-4311-aeb0-62112dbd9845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Format</value>
      <webElementGuid>08f28a85-ece9-4200-96da-5468ba75b2dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-menu-panel-315&quot;)/div[@class=&quot;mat-mdc-menu-content ng-tns-c681116372-387&quot;]/button[@class=&quot;mat-mdc-menu-item mat-mdc-focus-indicator mat-mdc-menu-trigger add-row-btn ng-tns-c681116372-387 ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-mdc-menu-item-text&quot;]/div[@class=&quot;flexbox-row gap-8 justify-content-between&quot;]</value>
      <webElementGuid>2de4a4d7-bb92-4d93-a5a8-7263b24c06de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-menu-panel-315']/div/button[2]/span/div</value>
      <webElementGuid>e0a7517e-8005-4161-9a92-4a1602f6731b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Month and Year Format'])[1]/following::div[2]</value>
      <webElementGuid>a7366053-605a-4b77-8aad-3079439f9e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clear'])[2]/following::div[10]</value>
      <webElementGuid>bd85f77d-0a1c-45b6-830f-ff13b8f97850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::div[3]</value>
      <webElementGuid>207519aa-a859-42fe-8d87-bd99d22470ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span/div</value>
      <webElementGuid>96bbdc82-7e84-462f-bb0b-173f27e29545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Format' or . = 'Format')]</value>
      <webElementGuid>13df8c4c-01cb-4cb1-89bb-e343973d4f86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
