<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Save_activatedBtnFormat</name>
   <tag></tag>
   <elementGuidId>fac0008a-3b67-40f0-9515-5a09ad54b1c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.activatedBtnFormat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/button[2]/span[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>22461aad-2bd9-4ccc-91fd-347325182a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../assets/images/ui-uplift-icons/global/bold-01.svg</value>
      <webElementGuid>9c3b6969-c282-4009-88ef-6c179700cf36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>activatedBtnFormat</value>
      <webElementGuid>adb6571e-d1eb-493d-ae9c-7c8ca86531a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dasboard-container layout-dashboard drawer-small&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;dashboard-main&quot;]/app-templates-dashboard[@class=&quot;ng-star-inserted&quot;]/mat-drawer-container[@class=&quot;mat-drawer-container countable-drawer templates mat-drawer-container-has-open&quot;]/mat-drawer-content[@class=&quot;mat-drawer-content overflow-hidden&quot;]/div[@class=&quot;contant-block-main flex-1 h-100 overflow-x-auto templates-content dashboard-main bg-white p-0 gap-0&quot;]/app-notes[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;notes dashboard-main ng-star-inserted&quot;]/div[@class=&quot;content-block-main h-100 d-flex flex-column flex-nowrap gap-20&quot;]/div[@class=&quot;notes-container d-flex flex-row flex-nowrap align-items-center w-100 gap-8 ng-star-inserted&quot;]/div[@class=&quot;datahtml w-100 ng-star-inserted&quot;]/app-fs-table[1]/div[@class=&quot;card overflow-hidden ng-star-inserted&quot;]/div[@class=&quot;card-body p-0 gap-20&quot;]/div[@class=&quot;flexbox-row align-items-center justify-content-between px-2 pt-3&quot;]/div[@class=&quot;button-group flex-1&quot;]/button[@class=&quot;fontStyle button-small-icon-action mdc-button mat-mdc-button mat-unthemed mat-mdc-button-base ng-star-inserted bg-primary-lighter_FS cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mdc-button__label&quot;]/img[@class=&quot;activatedBtnFormat&quot;]</value>
      <webElementGuid>b54b5f23-1afd-4400-a7ab-5fdb7abd2128</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button[2]/span[2]/img</value>
      <webElementGuid>d6778368-7569-4c56-9cfa-8f32521fab45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../../../assets/images/ui-uplift-icons/global/bold-01.svg']</value>
      <webElementGuid>7bb84738-729e-46c2-975f-2bb6f32723d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
