<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Current YearMON DD, 20XX</name>
   <tag></tag>
   <elementGuidId>7c55fa7f-2a28-4b64-afbb-39daa85eee76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.flexbox-row.gap-8.justify-content-end.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cdk-drop-list-0']/thead/tr/th[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cdd04e83-c3bd-4fdf-b46b-7ee7855d18a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flexbox-row gap-8 justify-content-end ng-star-inserted</value>
      <webElementGuid>eeb82a33-6097-47d8-b1b4-7467d3daa94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Current YearMON DD, 20XX</value>
      <webElementGuid>ebecc842-783a-4e78-8ec8-e3b80bb7913c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-drop-list-0&quot;)/thead[1]/tr[@class=&quot;mat-mdc-header-row mdc-data-table__header-row cdk-header-row ng-star-inserted&quot;]/th[@class=&quot;mat-mdc-header-cell mdc-data-table__header-cell cdk-header-cell fs-col-newadded text-end cdk-column-currYear mat-column-currYear fw-semibold ng-star-inserted&quot;]/span[@class=&quot;flexbox-row gap-8 justify-content-end ng-star-inserted&quot;]</value>
      <webElementGuid>dd3586ff-5905-4fdd-be6b-93a815e519f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cdk-drop-list-0']/thead/tr/th[4]/span</value>
      <webElementGuid>4e0b7353-7737-4416-b32f-abff57dd6016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[1]/following::span[16]</value>
      <webElementGuid>041fdbf9-7666-4d21-896f-9e7efa9ed967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Column'])[1]/following::span[16]</value>
      <webElementGuid>9a1fad10-9fd9-4bd9-857d-b8c3e106c220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]/span</value>
      <webElementGuid>7a221871-f394-4697-af3d-4a811dc9bf11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Current YearMON DD, 20XX' or . = 'Current YearMON DD, 20XX')]</value>
      <webElementGuid>518cefaf-e4be-41ac-8e08-dc345bfcd76c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
