<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Total</name>
   <tag></tag>
   <elementGuidId>ebeb7942-6b2b-4bcf-919e-5b0ba29ba9fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mat-mdc-menu-item.mat-mdc-focus-indicator.mat-mdc-menu-trigger.ng-star-inserted.ng-tns-c681116372-298.cdk-focused.cdk-mouse-focused > span.mat-mdc-menu-item-text > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-menu-panel-236']/div/button[4]/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0794fb2e-9a3b-413a-b937-d9702741e1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Total</value>
      <webElementGuid>b073cab8-0c4b-4d02-97c7-8f3965faaeee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-menu-panel-236&quot;)/div[@class=&quot;mat-mdc-menu-content ng-tns-c681116372-298&quot;]/button[@class=&quot;mat-mdc-menu-item mat-mdc-focus-indicator mat-mdc-menu-trigger ng-star-inserted ng-tns-c681116372-298 cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-mdc-menu-item-text&quot;]/span[1]</value>
      <webElementGuid>1db01c4f-d278-4eb6-a370-25f7e1d0086c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-menu-panel-236']/div/button[4]/span/span</value>
      <webElementGuid>194df112-4b60-41af-9986-0cf137448237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual'])[1]/following::span[2]</value>
      <webElementGuid>58adfe45-6872-45d7-9944-3133797e29dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prior Year'])[2]/following::span[4]</value>
      <webElementGuid>944f3fc2-5545-45db-a0e8-8f936bab68b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]/span/span</value>
      <webElementGuid>69c59d23-8d24-48c1-8dc5-0f111cdccd56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Total' or . = 'Total')]</value>
      <webElementGuid>68492644-7d9e-40ef-85c1-f8a566cdcc91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
