<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Year Only (20XX)</name>
   <tag></tag>
   <elementGuidId>2694e369-a407-4d3c-a210-aac38d524412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mat-mdc-menu-item.mat-mdc-focus-indicator.add-row-btn.ng-tns-c681116372-388.ng-star-inserted.cdk-focused.cdk-mouse-focused > span.mat-mdc-menu-item-text > div.flexbox-row.gap-8.justify-content-between > span.button-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-menu-panel-316']/div/button[3]/span/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b5910063-b465-46d1-8b4f-9340dbe3812f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-label</value>
      <webElementGuid>2e81a9b5-b90c-4e9f-a242-7f802766f88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Year Only (20XX)</value>
      <webElementGuid>a42c04e8-7daa-48c4-a708-3dec57f34696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-menu-panel-316&quot;)/div[@class=&quot;mat-mdc-menu-content ng-tns-c681116372-388&quot;]/button[@class=&quot;mat-mdc-menu-item mat-mdc-focus-indicator add-row-btn ng-tns-c681116372-388 ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-mdc-menu-item-text&quot;]/div[@class=&quot;flexbox-row gap-8 justify-content-between&quot;]/span[@class=&quot;button-label&quot;]</value>
      <webElementGuid>b5a9a4ba-1c29-4226-b0b5-be1d9b410ce3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-menu-panel-316']/div/button[3]/span/div/span</value>
      <webElementGuid>64a65e35-335a-4091-be8c-5889535ddf57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Short Format (MON DD, 20XX)'])[1]/following::span[2]</value>
      <webElementGuid>a82b2160-296e-45cb-bfdf-ebfd483f12f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Long Format (Month DD, 20XX)'])[1]/following::span[4]</value>
      <webElementGuid>567e2cde-3a55-4b4a-b648-f1e57de5f187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Year Only (20XX)']/parent::*</value>
      <webElementGuid>84885390-e50c-429d-9886-c3399b799822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/button[3]/span/div/span</value>
      <webElementGuid>cb94199a-8390-476b-b189-edbbc2d97ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Year Only (20XX)' or . = 'Year Only (20XX)')]</value>
      <webElementGuid>597d6c2d-2ee9-4f50-b32e-e0b249cb02e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
