<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Verify                                    Email</name>
   <tag></tag>
   <elementGuidId>fc8adf72-21d5-4da1-afc1-4d29c7a86044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mail']/div/div/table/tbody/tr[2]/td/div/table/tbody/tr[4]/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>13ab5133-3889-4ac2-a1f4-813f9521ee26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat.adinovis.com/setpassword?token=NTcwMTA2ZWItZGU1MS00YzE5LTlhM2UtMTI0ZDdjMTJiZDQ4</value>
      <webElementGuid>e2f3f241-6e8a-48de-8407-c1faf0af4b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify
                                    Email</value>
      <webElementGuid>efd8037c-d6fc-41c8-afc4-49432bd90ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mail&quot;)/div[1]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/table[1]/tbody[1]/tr[4]/td[1]/a[1]</value>
      <webElementGuid>c995e29b-8664-45dd-a7c3-c69f57c92fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Test/111224/Page_Inbox/iframe_Undo_ifmail</value>
      <webElementGuid>c58cbf89-d40e-47df-91f4-02dd7fae716b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mail']/div/div/table/tbody/tr[2]/td/div/table/tbody/tr[4]/td/a</value>
      <webElementGuid>71966c66-f0b5-4a90-b1c3-76f54df5ff70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Verify
                                    Email')]</value>
      <webElementGuid>79e130c2-21f8-4ef8-99e6-356faf7d4229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat.adinovis.com/setpassword?token=NTcwMTA2ZWItZGU1MS00YzE5LTlhM2UtMTI0ZDdjMTJiZDQ4')]</value>
      <webElementGuid>12b83f6f-97af-482a-9976-261744e5f46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>6c8fcfc9-966a-4666-868e-28c9027d7677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat.adinovis.com/setpassword?token=NTcwMTA2ZWItZGU1MS00YzE5LTlhM2UtMTI0ZDdjMTJiZDQ4' and (text() = 'Verify
                                    Email' or . = 'Verify
                                    Email')]</value>
      <webElementGuid>9f43c2da-2da8-426e-a9c1-f6dc09f4a0d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
