<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Undo_ifmail</name>
   <tag></tag>
   <elementGuidId>f8bc5a85-f459-454d-83c1-ebfe22482e0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ifmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a28494e5-a3ef-4d27-ba88-6a8a9042e945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ifmail</value>
      <webElementGuid>13253081-38d8-4389-a927-33fca9c5d988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>onloadifmail()</value>
      <webElementGuid>ff2c9fc2-5875-4ab4-8274-94915daf3219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifmail</value>
      <webElementGuid>aa518be2-3d4a-4049-bbf9-42098faab5d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>state</name>
      <type>Main</type>
      <value>full</value>
      <webElementGuid>686d50ef-d7a4-4f16-8acb-748905151522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ifmail&quot;)</value>
      <webElementGuid>ac714fad-ce7a-4508-aa8e-0e36058a5e16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifmail']</value>
      <webElementGuid>352c593d-5411-4687-b415-8e82742c4b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wmmailmain']/iframe</value>
      <webElementGuid>d1652424-6d95-41f6-b45b-c6a7b53c4530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/iframe</value>
      <webElementGuid>8ed2123f-5f87-4d0b-9361-3f060f1a9eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'ifmail' and @id = 'ifmail']</value>
      <webElementGuid>fff46b40-ef54-45b6-8158-6fdc22641fea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
