<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Re-enter Password_mat-mdc-checkbox-1-input</name>
   <tag></tag>
   <elementGuidId>4b5d80a2-3ceb-4033-a721-af0915a6ac8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-mdc-checkbox-1-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-mdc-checkbox-1-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b4e0acb-21d2-4df4-87e3-62de8f50803b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1cca2a25-79cb-4477-aedd-36ea09374885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-checkbox__native-control</value>
      <webElementGuid>677b176d-58d5-44ee-a1d2-9bcd24563db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-mdc-checkbox-1-input</value>
      <webElementGuid>370d8d7d-b8b1-4d2b-a276-ff57917721b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>5662fa88-6d42-47b4-9459-b0546f9fbcd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-checkbox-1-input&quot;)</value>
      <webElementGuid>96977945-9296-4eaf-bca8-a11f1021b03d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-mdc-checkbox-1-input']</value>
      <webElementGuid>96c31311-a39b-41dd-adcc-1921e0f56b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='mat-mdc-checkbox-1']/div/div/input</value>
      <webElementGuid>a9c6fbcd-d66f-4e9f-b3b0-ed21d7f9f00d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-checkbox/div/div/input</value>
      <webElementGuid>1d01289d-d7bc-4d54-958b-0c84bcfbebf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mat-mdc-checkbox-1-input']</value>
      <webElementGuid>ee202bb0-0e21-4bce-a9c3-7f9201351c18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
